title: "CMMC"
description: "Study notes on modern cryptography."
theme: minima

url: "https://cyc6221.github.io"
baseurl: "/CMMC"

# Author info
author: CY
email: s24343162@gmail.com
github_username: cyc6221

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  articles:
    output: true
    permalink: /articles/:path/

header_pages:
  - index.md
  - pages/about.md
  - pages/articles.md
  - pages/tags.md

plugins:
  - jekyll-git-metadata
  - jekyll-sitemap
