title: "CMMC â€” Cryptography Makes Me Cry"
description: "Study notes on modern cryptography."
theme: minima

url: "https://cyc6221.github.io"
baseurl: "/CMMC"

# Author info
# author: cyc6221
author: CY

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  articles:
    output: true
    permalink: /articles/:name/

header_pages:
  - index.md
  - pages/about.md
  - pages/articles.md
  - pages/tags.md

plugins:
  - jekyll-git-metadata
  - jekyll-sitemap
